name: Spark Cluster on Docker CI

on:
  schedule:
    - cron:  '0 0 * * MON-FRI'

jobs:
  
  base-image:
    
    name: Base Image
    runs-on: ubuntu-latest
        
    steps:
      - name: Build docker image
        env:
          BUILD_DATE: "$(date -u +'%Y-%m-%d')"
          SCALA_VERSION: "2.12.11"
        run: |
          docker build \
          --build-arg build_date="${BUILD_DATE}" \
          --build-arg scala_version="${SCALA_VERSION}" \
          -f buid/docker/base/Dockerfile \
          -t base:latest .
 